apiVersion: apps/v1
kind: Deployment
metadata:
  name: neogarage
  namespace: neotech
spec:
  replicas: 2  # Nombre d'instances
  selector:
    matchLabels:
      app: neogarage
  template:
    metadata:
      labels:
        app: neogarage
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64 
      containers:
        - name: neogarage
          image: lionel1109/neogarage:latest
          ports:
            - containerPort: 3000  # Port d'écoute de l'application
          resources:
            requests:
              memory: "256Mi"    # Mémoire minimum demandée
              cpu: "100m"       # 0.1 CPU minimum demandé
            limits:
              memory: "512Mi"    # Mémoire maximale allouée
              cpu: "500m"       # 0.5 CPU maximal alloué
