apiVersion: v1
kind: Service
metadata:
  name: neogarage-service
  namespace : neogarage
spec:
  type: NodePort  # Expose l’application sur un port du nœud
  selector:
    app: neogarage
  ports:
    - protocol: TCP
      port: 443 # Port du service interne
      port: 80 # Port du service interne
      targetPort: 3008  # Port du container
      nodePort: 30014 # Port exposé sur le nœud (doit être entre 30000-32767)
