apiVersion: v1
kind: Service
metadata:
  name: neogarage-service
  namespace: neogarage
spec:
  type: NodePort
  selector:
    app: neogarage
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32443 # Tu peux choisir un port entre 30000 et 32767
